services:
  - type: web
    name: socket-chat-app
    env: node
    buildCommand: |
      cd socket-chat-frontend && npm install && npm run build
      cp -r build ../socket-chat-backend/build
      cd ../socket-chat-backend && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    rootDir: socket-chat-backend
