services:
  - type: web
    name: chat-backend
    env: node
    plan: free
    rootDir: socket-chat-backend
    buildCommand: |
      cd ../socket-chat-frontend && npm install && npm run build &&
      cp -r ../socket-chat-frontend/build ./build &&
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
