services:
  - type: web
    name: socket-chat-app
    env: docker
    dockerfilePath: socket-chat-backend/Dockerfile
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: "" # No build step; it's done inside Dockerfile
    startCommand: "" # CMD in Dockerfile handles this
    envVars:
      - key: PORT
        value: 5000
